### ISSUE TITLE
Error: Cannot find module 'qrCode-terminal' in my project

### ISSUE THREAD

**Issue by glaucioripol** [gtanner/qrcode-terminal#42]
my code sample

```js
const qrCode = require('qrCode-terminal')

module.exports.showQrCodeOnTerminal = qr => qrCode.generate(qr, { small: true })
```

Exception:

glaucio@ ~/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho (main) $ npm start

> robo@1.0.0 start /home/glaucio/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho
> node src/index.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

**Error: Cannot find module 'qrCode-terminal'**
Require stack:
- /home/glaucio/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho/src/services/showQrCodeOnTerminal.js
- /home/glaucio/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho/src/services/index.js
- /home/glaucio/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/glaucio/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho/src/services/showQrCodeOnTerminal.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/glaucio/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho/src/services/showQrCodeOnTerminal.js',
    '/home/glaucio/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho/src/services/index.js',
    '/home/glaucio/workspace/glaucio/redirecionarMsgsWhatsAppRodolpho/src/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robo@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.****

**Comment by cinderblock** [comment]
1. You should post **your** code when asking for help. Just seeing `npm start` is usually not enough.
2. Please use code blocks for code/log output. It is **much** easier to read. Use triple backticks (` ``` `) to make it look like this:
    ```js
    console.log('Hello, World.");
    ```
3. `require` and `import` are case-sensitive. You have `'qrCode-terminal'`. You need `'qrcode-terminal'`.

**Comment by glaucioripol** [comment]
module where I declared the use of lib
```js
const qrCode = require('qrCode-terminal')

module.exports.showQrCodeOnTerminal = qr => qrCode.generate(qr, { small: true })
```

**Comment by cinderblock** [comment]
Thank you for posting the code example. Thank you extra for using code blocks.

If you want to be extra awesome, edit your initial comment to use code blocks.

Please read my third point again to see the solution you need :)
