### ISSUE TITLE
Failed to generate qrcode. Error: bad rs block 

### ISSUE THREAD

**Issue by jrvidotti** [gtanner/qrcode-terminal#47]
I am getting this error since I moved my project to Typescript (with CJS was working fine):

generate('1@myDUfOyRFgL650YXw7hqOIh97DiPfCTSWvL/lWY0xk5eMO1/RwU2BJQqyKwKCfy4YQ89jbcJpIs9pA==,y+0gkbGCtydkADbHaPz4BmDHh/Htmvck1+ZJzDANyHA=,39iJKFq9jMqBL3QPcKUY4w==')

Error: bad rs block @ typeNumber:1/errorCorrectLevel:undefined
    at Function.QRRSBlock.getRSBlocks (/Users/junior/dev/bot-whatsapp/node_modules/qrcode-terminal/vendor/QRCode/QRRSBlock.js:261:9)
    at QRCode.make (/Users/junior/dev/bot-whatsapp/node_modules/qrcode-terminal/vendor/QRCode/index.js:58:30)
    at generate (/Users/junior/dev/bot-whatsapp/node_modules/qrcode-terminal/lib/main.js:35:16)
    at /Users/junior/dev/bot-whatsapp/src/main.ts:33:17
    at step (/Users/junior/dev/bot-whatsapp/src/main.ts:52:23)
    at Object.next (/Users/junior/dev/bot-whatsapp/src/main.ts:33:53)
    at fulfilled (/Users/junior/dev/bot-whatsapp/src/main.ts:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by wedreamer** [comment]
```ts
// import { generate } from "qrcode-terminal"; -> err
const qrcode = require('qrcode-terminal');

const qr = `1@DYZM9Y7+JBq1c+0TigkfeKUFj5y2bEJko/4MRz2EU3nQpGxdDgVYMqCwKdaXdzDsTKjbYkc8eswoSg==,kEkbz6rn1k3MvmZ+HhsHQusz6pgmWqzgWY55aZtM21o=,AqWACiDRD+oJ+Sq/72WXWQ==`

qrcode.generate(qr)

```

**Comment by jantimon** [comment]
This would be fixed by #49

**Comment by pedropedruzzi** [comment]
PR #49 is still not merged. Package is apparently abadoned.

If you ran into this issue, the most likely cause is a bug in this package that triggers when it's imported like this: `import { generate } from 'qrcode-terminal';`. The workaround is to import like this: `import qrcode from 'qrcode-terminal';`
